name: u_store
description: "A new Flutter project."


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

#-------------------packages----------------#
dependencies:
  flutter:
    sdk: flutter

  #-------------------utility packages----------------#
  http: ^1.2.2
  intl: ^0.19.0
  logger: ^2.4.0
  url_launcher: ^6.3.0
  flutter_native_splash: ^2.4.1
  smooth_page_indicator: ^1.2.0+3
  carousel_slider: ^5.0.0
  
  #-------------------icons----------------#
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.8

  #-------------------state management----------------#
  get: ^4.6.6
  get_storage: ^2.1.1

  #-------------------product specific----------------#

#-------------------packages end----------------#


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true


  #-------------------local assets----------------#

  assets:
    - assets/images/
    - assets/images/animations/
    - assets/images/banners/
    - assets/images/content/
    - assets/images/onboarding/
    - assets/images/products/
    - assets/images/reviews/
    - assets/logos/
    - assets/logos/social_logo/
    - assets/icons/
    - assets/icons/brands/
    - assets/icons/categories/
    - assets/icons/payment_methods/


  #-------------------local fonts----------------#

  fonts:
    - family: poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800